# top level stuff you probably don't need to touch
highlighter: rouge 
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: alaniahodge.com/
baseurl: /
title: Alania Marie Hodge 
author: Alania Marie Hodge 
description: Personal blog and resume
avatar: profile.png
email: amhodge4@yahoo.com
github: lphipena.github.io.git # username
linkedin: alania-hodge-a70658a4
tel: +407 452 2729
tel_full: tel:+2313213211
google_maps: 'https://www.google.com/maps/place/6372+Raleigh+St,+Orlando,+FL+32835'
address: 6372 Raleigh Street apt. 1904
postcode: 32835 
city: Orlando, FL
country: United States 
#Comment out if you don't want disqus 
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
